// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU0rHgBCCEqMyPuCAvqJ5gg4dAI4-q3Vo',
    appId: '1:576053121844:web:e99c1a4f263f408ac74b61',
    messagingSenderId: '576053121844',
    projectId: 'fastbite-d61b7',
    authDomain: 'fastbite-d61b7.firebaseapp.com',
    storageBucket: 'fastbite-d61b7.firebasestorage.app',
    measurementId: 'G-L5DEKPS6RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr9Acg9pbhWxChfbzWrD-MZRXbW3nRbYY',
    appId: '1:576053121844:android:90c7e86701e517b0c74b61',
    messagingSenderId: '576053121844',
    projectId: 'fastbite-d61b7',
    storageBucket: 'fastbite-d61b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS2--ZP_4I3RViP_MZTfhn1deS1518VD8',
    appId: '1:576053121844:ios:32758b4741208e5fc74b61',
    messagingSenderId: '576053121844',
    projectId: 'fastbite-d61b7',
    storageBucket: 'fastbite-d61b7.firebasestorage.app',
    iosClientId: '576053121844-hf7kuhuuq74culq66u11gbap7dsgk1hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastbiteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS2--ZP_4I3RViP_MZTfhn1deS1518VD8',
    appId: '1:576053121844:ios:32758b4741208e5fc74b61',
    messagingSenderId: '576053121844',
    projectId: 'fastbite-d61b7',
    storageBucket: 'fastbite-d61b7.firebasestorage.app',
    iosClientId: '576053121844-hf7kuhuuq74culq66u11gbap7dsgk1hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastbiteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU0rHgBCCEqMyPuCAvqJ5gg4dAI4-q3Vo',
    appId: '1:576053121844:web:0c291a79c10b91c8c74b61',
    messagingSenderId: '576053121844',
    projectId: 'fastbite-d61b7',
    authDomain: 'fastbite-d61b7.firebaseapp.com',
    storageBucket: 'fastbite-d61b7.firebasestorage.app',
    measurementId: 'G-JD18R6KF9N',
  );
}
