// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaCsPVVD_JSLXl3AbbdPsjVRk6KGDdngM',
    appId: '1:590773816726:web:38812e2e667cdc4338a1b7',
    messagingSenderId: '590773816726',
    projectId: 'event-checkin-app-d2aa5',
    authDomain: 'event-checkin-app-d2aa5.firebaseapp.com',
    storageBucket: 'event-checkin-app-d2aa5.firebasestorage.app',
    measurementId: 'G-2D985HER5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOrbzauZJpPp0KU-sorovQDybZAWoWBCg',
    appId: '1:590773816726:android:19c101b6ba90a64438a1b7',
    messagingSenderId: '590773816726',
    projectId: 'event-checkin-app-d2aa5',
    storageBucket: 'event-checkin-app-d2aa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIsPsdlJtJ_wEiyLY38IjnIocdq-dLND8',
    appId: '1:590773816726:ios:2fa044066c8a518338a1b7',
    messagingSenderId: '590773816726',
    projectId: 'event-checkin-app-d2aa5',
    storageBucket: 'event-checkin-app-d2aa5.firebasestorage.app',
    iosBundleId: 'com.example.eventCheckinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIsPsdlJtJ_wEiyLY38IjnIocdq-dLND8',
    appId: '1:590773816726:ios:2fa044066c8a518338a1b7',
    messagingSenderId: '590773816726',
    projectId: 'event-checkin-app-d2aa5',
    storageBucket: 'event-checkin-app-d2aa5.firebasestorage.app',
    iosBundleId: 'com.example.eventCheckinApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaCsPVVD_JSLXl3AbbdPsjVRk6KGDdngM',
    appId: '1:590773816726:web:dbe133fbb54f872038a1b7',
    messagingSenderId: '590773816726',
    projectId: 'event-checkin-app-d2aa5',
    authDomain: 'event-checkin-app-d2aa5.firebaseapp.com',
    storageBucket: 'event-checkin-app-d2aa5.firebasestorage.app',
    measurementId: 'G-EJBPHXP89S',
  );
}
